name: PerchBoosters
version: '${version}'
main: dev.ev1dent.perchboosters.BoosterPlugin
api-version: '1.21'
depends:
  - LuckPerms
commands:
  perchboosters:
    description: "Booster Plugin"
    permission: "perchboosters.use"
    usage: "/<command> [reset | reload] <player>"
