name: PerchRewards
version: '${version}'
main: dev.ev1dent.perchrewards.RewardPlugin
api-version: '1.21'
depends:
  - LuckPerms
commands:
  perchrewards:
    description: "Rewards Plugin"
    permission: "perchrewards.use"
    usage: "/<command> [check|reset|reload] <player> [first|monthly|all] [month] [year]"
    aliases:
      - pr
      - pb
      - prp
